### ISSUE TITLE
[BUG] Alarm Icon does not go away. 

### ISSUE THREAD

**Issue by amunizp** [NeonGeckoCom/skill-alerts#108]
### Description

Hi, I see the alarm Icon showed up when I set up an alarm for tonight. But I then cancelled all timers, all alarms and all reminders. Neon agrees with me that I have non scheduled. The alarm clock Icon is still showing. on the topleft. 

### Steps to Reproduce

- Create an alarm. 
- Observe the Icon with the alarm symbol showing. 
- Disable the alarm.
- Icon remains.

**Comment by NeonDaniel** [comment]
Sorry, I missed this; it seems I wasn't properly subscribed to GitHub notifications here. I was unable to reproduce this issue, can you confirm this is still happening or if it has been resolved since the issue was opened?

Appears related to https://github.com/NeonGeckoCom/skill-alerts/pull/90

**Comment by amunizp** [comment]
I believe it was an older version of neon.i am sure #90 is the same thing. Thank you!
