### ISSUE TITLE
[FEAT] Support neon-iris

### ISSUE THREAD

**Issue by mikejgray** [NeonGeckoCom/skill-alerts#133]
### Objective

Currently, when an alert is scheduled, it does not get back to the gradio or websat interfaces for neon-iris. You can see the reminder in the neon-skill logs but there's no transport back to the web interfaces.

### Initial Implementation Requirements

- Allow at least spoken reminders to go back to the profile that created them
- Optionally, emit the reminder event data so that the web interface(s) can also display something on the screen

**Comment by NeonDaniel** [comment]
Relates to https://github.com/NeonGeckoCom/neon-hana/issues/6

**Comment by NeonDaniel** [comment]
#135 adds an event for expired alerts

**Comment by NeonDaniel** [comment]
Still needed:
- documentation of `neon.alert` Messages
- validation of backwards-compat. with local and existing server implementations
- implementation of a client handler to validate emitted data/context
