### ISSUE TITLE
Icons not removed when timer canceled

### ISSUE THREAD

**Issue by MyNameIs-13** [NeonGeckoCom/skill-alerts#72]
(Mycroft2 Prod Unit)

steps to reproduce:
- create a timer: «set a 5 minute timer»
- cancel timer (before it's over): «cancel all timer»

-> top left of the homescreen has a 'stopwatch' icon

**Comment by NeonDaniel** [comment]
I was able to reproduce this issue; notifications are dismissed when alerts are removed via GUI, but not via voice
